# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Candensa < Formula
  desc "Candensa CLI — deploy anything, on any infrastructure, from one control plane."
  homepage "https://candensa.sh"
  version "0.3.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/candensa/engine/releases/download/v0.3.0/candensa_0.3.0_darwin_amd64.tar.gz"
      sha256 "0c7c89b3fec6b4c7d3dae2cd6be8c16ff85516e2e873bce5dad1b9a38c5a513d"

      define_method(:install) do
        bin.install "candensa"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/candensa/engine/releases/download/v0.3.0/candensa_0.3.0_darwin_arm64.tar.gz"
      sha256 "ef175f69cee41ce3de97248e3b89ae7705cfdddfbb648a11dadb4585692e6b59"

      define_method(:install) do
        bin.install "candensa"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/candensa/engine/releases/download/v0.3.0/candensa_0.3.0_linux_amd64.tar.gz"
      sha256 "1ef13600e39a53739d8ea3c499123f6495406e8d9bab87e060f664bb205dcef3"
      define_method(:install) do
        bin.install "candensa"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/candensa/engine/releases/download/v0.3.0/candensa_0.3.0_linux_arm64.tar.gz"
      sha256 "bc917c7d538e2ea33cbf8048b8a29a6b6df2b7446fa00db20ab7a78782bcfdc7"
      define_method(:install) do
        bin.install "candensa"
      end
    end
  end

  test do
    system "#{bin}/candensa", "--version"
  end
end
